---

- name: Ubuntu day2ops
  hosts: localhost
  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: add apt repo for remmina
      become: true
      apt_repository:
        repo: ppa:remmina-ppa-team/remmina-next
    - name: Install a list of packages
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - jq
          - jo
          - iptables
          - sshuttle
          - remmina
          - remmina-plugin-rdp
          - remmina-plugin-secret
          - wireshark
          - cntlm
          - tree
          - direnv
          - bison
          - curl
          - grep
          - gzip
          - less
          - nmap
          - openssl
          - sshpass
          - tar
          - unzip
          - vim
          - wget
          - whois
          - zip
          # git credential helper
          - libsecret-1-0
          - libsecret-1-dev
          # END git credential helper
          - openconnect
          - nautilus-dropbox
          - net-tools
          - kazam
          - virtualbox
          - tmux
          - golang-cfssl
          # bosh dependencies https://bosh.io/docs/cli-v2-install/
          - build-essential
          - zlibc
          - zlib1g-dev
          - ruby
          - ruby-dev
          - openssl
          - libxslt1-dev
          - libxml2-dev
          - libssl-dev
          - libreadline7
          - libreadline-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          # END bosh dependencies
          # ansible dependencies https://bosh.io/docs/cli-v2-install/
          - python3-venv
          # END ansible dependencies
    - name: Download binary files and place on PATH
      become: yes
      get_url: url={{ item.value.url }} dest=/usr/local/bin/{{ item.value.name }} mode=0755 force=yes
      with_dict: "{{ binaries }}"
      vars:
        binaries:
          kubectl:
            name: kubectl
            url: https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
          bosh-cli:
            name: bosh
            url: https://github.com/cloudfoundry/bosh-cli/releases/download/v5.5.1/bosh-cli-5.5.1-linux-amd64
