#!/bin/sh

action=${1:-'build'}
configs_dir=~/.ssh/configs

if [ "$action" = "build" ]; then
  cat ~/dotfiles/sshconfig $configs_dir/* > ~/.ssh/config 2>/dev/null
  echo 'sshconfig generated'
elif [ "$action" = "list" ]; then
  # sshconfig list to see list of client specific 
  # configuration files present in configs folder
  # ls -l1 $configs_dir | tail -n+2 | awk '{print $9}'
  find "$configs_dir" -type f -exec basename {} \;
elif [ "$action" = "rm" ]; then
  # sshconfig rm <filename>
  file="$2"
  rm -f "$configs_dir/$file"
  $0 build
elif [ "$action" = "create" ]; then
  file="$2"
  $EDITOR "$configs_dir/$file"
else
  echo 'Usage: sshconfig build|list|rm|create <filename>'
fi
